# SPDX-License-Identifier: Apache-2.0
# Copyright Red Hat Inc. and Hibernate Authors

name: 'Teardown Documentation Preview'
description: 'Remove the preview deployment and update the PR comment to indicate the preview is no longer available'

inputs:
  pr-number:
    description: 'Pull request number'
    required: true

runs:
  using: "composite"
  steps:
    - name: Teardown Surge preview
      shell: bash
      env:
        DEPLOY_DOMAIN: "${{ github.event.repository.name }}-pr-${{ inputs.pr-number }}-preview.surge.sh"
      run: |
        npx --ignore-scripts surge@0.31.1 teardown "https://${DEPLOY_DOMAIN}"
      continue-on-error: true

    - name: Update PR comment to indicate preview is removed
      uses: ./actions/upsert-pr-comment
      with:
        marker: '<!-- docs-preview -->'
        pr-number: ${{ inputs.pr-number }}
        update-only: 'true'
        content: |-
          ### Documentation Preview

          _This preview has been removed following the closure of this PR._
      continue-on-error: true
