name: GitHub Actions linter

on:
  pull_request:
  workflow_call:

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Detect workflow changes
        id: change-detector
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          set -e # Fail if the gh command fails (e.g. can't connect, ...)
          # JQ checks if ANY file path starts with our target directory, returning a literal "true" or "false"
          IS_CHANGED=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json files --jq 'any(.files[]; .path | startswith(".github/workflows/"))')
          # Output the result directly to GitHub Actions
          echo "any_workflow_changed=$IS_CHANGED" >> "$GITHUB_OUTPUT"
      - name: Shallow check out repository code
        if: steps.change-detector.outputs.any_workflow_changed == 'true'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
      # https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
      - name: Download and run actionlint
        if: steps.change-detector.outputs.any_workflow_changed == 'true'
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color