# SPDX-License-Identifier: Apache-2.0
# Copyright Red Hat Inc. and Hibernate Authors

name: PR cleanup

on:
  workflow_call:

defaults:
  run:
    shell: bash

permissions: { }

jobs:
  setup:
    name: Resolve configuration
    runs-on: ubuntu-latest
    outputs:
      docs-preview: ${{ steps.config.outputs.docs-preview }}
    steps:
      - name: Resolve feature flags
        id: config
        uses: hibernate/.github/actions/resolve-ci-config@47bbb242502916bdd26d33ad829e2fe784b694f6
        with:
          repository: ${{ github.repository }}
          branch: ${{ github.event.pull_request.base.ref }}

  teardown-docs-preview:
    name: Teardown docs preview
    needs: setup
    if: needs.setup.outputs.docs-preview == 'true'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Teardown Surge preview
        shell: bash
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_PREVIEW_TOKEN }}
          DEPLOY_DOMAIN: "${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}-preview.surge.sh"
        run: |
          npx --ignore-scripts surge@0.31.1 teardown "https://${DEPLOY_DOMAIN}"
        continue-on-error: true

      - name: Update PR comment to indicate preview is removed
        uses: hibernate/.github/actions/upsert-pr-comment@47bbb242502916bdd26d33ad829e2fe784b694f6
        with:
          marker: '<!-- docs-preview -->'
          pr-number: ${{ github.event.pull_request.number }}
          update-only: 'true'
          content: |-
            ### Documentation Preview

            _This preview has been removed following the closure of this PR._
        continue-on-error: true
